### ISSUE TITLE
1.7版本VideoPlayerView  存在 NullPointerException

### ISSUE THREAD

**Issue by marlboro3420** [huyongli/TigerVideo#9]
`   java.lang.NullPointerException: Attempt to read from field 'cn.ittiger.player.ui.VideoControllerView cn.ittiger.player.ui.StandardVideoView.mVideoControllerView' on a null object reference
                                                                      at cn.ittiger.player.VideoPlayerView.onExitSmallWindowPlay(VideoPlayerView.java:583)
                                                                      at cn.ittiger.player.VideoPlayerView.toggleSmallWindow(VideoPlayerView.java:530)
                                                                      at cn.ittiger.player.VideoPlayerView.onAttachedToWindow(VideoPlayerView.java:364)
                                                                      at android.view.View.dispatchAttachedToWindow(View.java:14551)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2839)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2846)`

VideoPlayerView 的583行报错，多操作几下这个错误挺容易出现的

**Comment by marlboro3420** [comment]
我在

` VideoPlayerView smallWindowView = (VideoPlayerView) windowContent.findViewById(R.id.vp_small_window_view_id);`

行下面加了段

```
 if (smallWindowView == null) {
     TextureView textureView = createTextureView();
     mVideoTextureViewContainer.addView(textureView);
     PlayerManager.getInstance().setTextureView(textureView);
     return;
 }
```

暂时不崩溃了，感觉差不多好了，大佬看看有什么问题没
